apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: online-spaza
type: Opaque
stringData:
  password: "Qwbrty!"
  username: "root"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: online-spaza
type: Opaque
stringData:
  secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
